### ISSUE TITLE
Doesn't recognize "custom" QR codes

### ISSUE THREAD

**Issue by grr** [dlbeer/quirc#1]
qrtest couldn't find any codes in the examples of custom qr codes on the wikipedia page:
https://en.wikipedia.org/wiki/QR_code#Variants

**Comment by stuartpb** [comment]
These QR codes have since been deleted, so I can't take a direct look to check, but many "custom" QR codes that form the code around an image do so by, essentially, [adding errors to the QR code in non-essential locations](http://research.swtch.com/qart), so it's wholly possible that these codes were just too broken to read.

**Comment by dlbeer** [comment]
I'm guessing these will work now anyway. I recently fixed the Reed-Solomon decoder, which was effectively non-functional for quite a while previously.

(https://github.com/dlbeer/quirc/commit/87e79e769b90de65037226bb495207730c8fb42a)
